name: "Docker Build (composite)"
description: "Reusable composite action for Docker builds"
inputs:
  context:
    default: "."
    required: false
  file:
    default: "./Dockerfile"
    required: false
  build_args:
    default: ""
    required: false
  platforms:
    default: "linux/amd64"
    required: false
  push:
    default: "false"
    required: false
runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: ${{ inputs.push }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build_args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
