name: docker-build-push
on:
  workflow_call:
    inputs:
      image_name:
        description: "Full image name, e.g., ghcr.io/org/app"
        required: true
        type: string
      context:
        default: "."
        required: false
        type: string
      file:
        default: "./Dockerfile"
        required: false
        type: string
      build_args:
        default: ""
        required: false
        type: string
      platforms:
        default: "linux/amd64"
        required: false
        type: string
      push:
        default: "true"
        required: false
        type: string
      tags:
        default: ""
        required: false
        type: string
      provenance:
        default: "false"
        required: false
        type: string
      sbom:
        default: "false"
        required: false
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: false
      REGISTRY_PASSWORD:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR (GITHUB_TOKEN)
        if: ${{ !secrets.REGISTRY_USERNAME }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to custom registry (optional)
        if: ${{ secrets.REGISTRY_USERNAME }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.image_name && fromJSON('["' + inputs.image_name + '"]')[0].split('/')[0] || 'ghcr.io' }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image_name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.push }}
          platforms: ${{ inputs.platforms }}
          tags: ${{ inputs.tags != '' && inputs.tags || steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: ${{ inputs.provenance }}
          sbom: ${{ inputs.sbom }}

      - name: Generate SBOM (optional)
        if: ${{ inputs.sbom == 'true' }}
        uses: anchore/sbom-action@v0
        with:
          image: ${{ inputs.image_name }}:latest
          format: spdx-json
          artifact-name: sbom.spdx.json
